//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KütüphaneEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class kayitlar
    {
        public int kayitlarid { get; set; }
        public Nullable<int> okuyucuid { get; set; }
        public Nullable<int> okudugukitapid { get; set; }
        public Nullable<int> aldigikurumid { get; set; }
        public string alisTarih { get; set; }
        public string iadeTarih { get; set; }
    
        public virtual kitaplar kitaplar { get; set; }
        public virtual kurumlar kurumlar { get; set; }
        public virtual okuyucular okuyucular { get; set; }
    }
}
