//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KütüphaneEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class kitaplar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public kitaplar()
        {
            this.kayitlar = new HashSet<kayitlar>();
        }
    
        public int kitapno { get; set; }
        public Nullable<int> isbno { get; set; }
        public string kitapadi { get; set; }
        public Nullable<int> yazarno { get; set; }
        public Nullable<int> turno { get; set; }
        public Nullable<int> kurumid { get; set; }
        public Nullable<int> sayfasayisi { get; set; }
        public string kitapdurum { get; set; }
        public string kitapresim { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<kayitlar> kayitlar { get; set; }
        public virtual kurumlar kurumlar { get; set; }
        public virtual turler turler { get; set; }
        public virtual yazarlar yazarlar { get; set; }
    }
}
