//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KütüphaneEntity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TurkiyeKutuphaneEntityEntities2 : DbContext
    {
        public TurkiyeKutuphaneEntityEntities2()
            : base("name=TurkiyeKutuphaneEntityEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<iller> iller { get; set; }
        public virtual DbSet<kayitlar> kayitlar { get; set; }
        public virtual DbSet<kitaplar> kitaplar { get; set; }
        public virtual DbSet<kurumlar> kurumlar { get; set; }
        public virtual DbSet<okuyucular> okuyucular { get; set; }
        public virtual DbSet<personeller> personeller { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<turler> turler { get; set; }
        public virtual DbSet<yazarlar> yazarlar { get; set; }
    }
}
