//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KütüphaneEntity
{
    using System;
    using System.Collections.Generic;

    public partial class okuyucular
    {
        private string _okuyucuad;
        private string _okuyucusoyad;

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public okuyucular()
        {
            this.kayitlar = new HashSet<kayitlar>();
        }

        public int okuyucuid { get; set; }
        public string okuyucuad
        {
            get { return _okuyucuad; }
            set { _okuyucuad = value.ToLower(); }
        }
        public string okuyucusoyad
        {
            get { return _okuyucusoyad; }
            set { _okuyucusoyad = value.ToLower(); }
        }
        public string okuyucuTC { get; set; }
        public string okuyucuDogumTarih { get; set; }
        public string okuyucuTel { get; set; }
        public string okuyucuSifre { get; set; }
        public string okuyucuPuan { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<kayitlar> kayitlar { get; set; }
    }
}
