//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KütüphaneEntity
{
    using System;
    using System.Collections.Generic;

    public partial class personeller
    {
        private string _personelad;
        private string _personelsoyad;

        public int personelid { get; set; }
        public string personelad
        {
            get { return _personelad; }
            set { _personelad = value.ToLower(); }
        }
        public string personelsoyad
        {
            get { return _personelsoyad; }
            set { _personelsoyad = value.ToLower(); }
        }
        public string personelTC { get; set; }
        public string personelDogumTarih { get; set; }
        public string personelTel { get; set; }
        public Nullable<int> personelKurumid { get; set; }
        public string personelSifre { get; set; }

        public virtual kurumlar kurumlar { get; set; }
    }
}
